# Generated by Django 5.2.9 on 2025-12-05 10:33

from django.db import migrations

def add_default_positions(apps, schema_editor):
    Position = apps.get_model('employee_register', 'Position')
    positions = [
        'Manager',
        'Software Developer',
        'Data Scientist',
        'Project Manager',
        'HR',
        'Sales Representative',
        'Graphic Designer',
        'Accountant',
    ]
    for position_title in positions:
        Position.objects.create(title=position_title)

class Migration(migrations.Migration):

    dependencies = [
        ("employee_register", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_positions),
    ]
